import { Platform } from "react-native";
import NearbyYourLocation from "../screens/ClientSideScreens/HomeScreen/NearbyYourLocation";


export const AppUrl = Platform.OS == 'ios' ? 'https://apps.apple.com/in/app/digital-health-news/id6473037148' : 'https://play.google.com/store/apps/details?id=com.dhn';

// type 0 = android
// type 1 = ios
export const NavigationScreens = {
    SplashScreen: 'Splash Screen',
    SignUpScreen: 'Sign Up Screen',
    SignInScreen:'Sign In Screen',
    PasswordAndOtpScreen:'PasswordAndOtpScreen',
    EmailVerificationScreen:'EmailVerification Screen',
    FillProfileScreen:'Fill Profile Screen',
    MyBookMarkScreen:'My Book Mark Screen',
    MyProfileScreen:'My Profile Screen',
    SwitchToProfessionalsScreen:'SwitchToProfessionals Screen',
    TransactionHistoryScreen:'TransactionHistory Screen',
    PasswordScreen: 'Password Screen',
    NewpasswordScreen:'NewpasswordScreen',
    ForgotPasswordScreen: 'Forgot Password Screen',
    OTPScreen:'OTPScreen',
    OurServicesScreen:'OurServices Screen',
    ReserveNowServicesScreen:'ReserveNowServicesScreen',
    ServiceDetailsScreen:'ServiceDetails Screen',
    OurpackagesScreen:'Ourpackages Screen',
    OurPackageDetailScreen:'OurPackageDetail Screen',
    VerificationScreen: 'Verification Screen',
    WelcomeOnboardScreen: 'Welcome Onboard Screen',
    ProceedWithoutScreen:'ProceedWithoutScreen',
    HomeScreen: 'Home Screen',
    AddAddressScreen: 'AddAddressScreen',
    SelectDeliveryLocationScreen: 'SelectDeliveryLocationScreen',
    SearchLocationScreen: 'SearchLocationScreen',
    ConformLocationScreen: ' ConformLocationScreen',
    DeliveryScreen:'DeliveryScreen',
    SalonScreen:'SalonScreen',
    ScheduledeliveryScreen:'ScheduledeliveryScreen',
    SchedulesalonScreen:'SchedulesalonScreen',
    OTPScreen:'OTPScreen',
    OurGalleryScreen:'OurGallery Screen',
    ReviewsDetailScreen:'ReviewsDetail Screen',
    BookAppointmentScreen:'BookAppointment Screen',
    VideoPlayerScreen: 'Video Player Screen',
    MenuScreen: 'Menu Screen',
    ExploreScreen: 'Explore',
    MyBookingScreen:'My Booking',
    InboxScreen:'Inbox',
    ChatScreen:'Chat Screen',
    ProfileScreen:'Profile',
    DetailScreen: 'Detail Screen',
    EventsDetailScreen: 'Events Detail Screen',
    PaymentMethodScreen:'PaymentMethod Screen',
    LiveTrackingClientSideScreen:'LiveTrackingClientSideScreen',
    OrderProcessingScreenClientSideScreen:'OrderProcessingScreenClientSideScreen',
    HomeTab: 'Home Tab',
    SubCategoryScreen: 'Sub Category Screen',
    NewpasswordScreen: 'NewpasswordScreen',
    EditProfileScreen: 'Edit Profile Screen',
    ChangePasswordScreen: 'Change Password Screen',
    NotificationScreen:'Notification Screen',
    NewpasswordScreen:"NewpasswordScreen",
    HaircutScreen:'Haircut Screen',
    MackupScreen:'Mackup Screen',
    ManicureScreen:'Manicure Screen',
    MassageScreen:'Massage Screen',
    SearchFilterScreen:'SearchFilter Screen',
    BookingHoursScreen:'Booking Hours Screen',
    NearbyYourLocationScreen:'NearbyYourLocation Screen',
    ClientSettingScreen:'ClientSettingScreen',
    FacilityListScreen:'FacilityListScreen',
    SalonProffListScreen:'SalonProffListScreen',
    SalonProfServicesScreen:'SalonProfServicesScreen',
    OurProfessionalDetailsScreen:'OurProfessionalDetails Screen',
    ProfessionalInfoScreen:'ProfessionalInfoScreen',
    CancelbookingScreen:'Cancelbooking Screen',
    EditProfileScreen:'EditProfile Screen',
    SecurityScreen:'Security Screen',
    PrivacyPolicyScreen:'PrivacyPolicy Screen',
    ReviewSummaryScreen:'ReviewSummary Screen',
    EReceiptScreen:'EReceiptScreen',
    Booking:'Booking',

    ProfessionalAboutUsScreen:'ProfessionalAboutUsScreen',
    ProfessionalGalleryScreen:'ProfessionalGalleryScreen',
    ProfessionalPackageScreen:'ProfessionalPackageScreen',
    ProfessionalReviewScreen:'ProfessionalReviewScreen',
    ProfessionalServicesScreen:'ProfessionalServicesScreen',

    ProfessionalBottomTab:'ProfessionalBottom Tab',
    ProfessionalHomeScreen:'ProfessionalHome Screen',
    ProfessionalFacilitiesScreen:'ProfessionalFacilities Screen',
    ProfessionalServicesScreen:'ProfessionalServices Screen',
    ProfessionalProfileScreen:'ProfessionalProfile Screen',
    ProfessionalEditProfileScreen:'ProfessionalEditProfile Screen',
    ProfessionalSecurityScreen:'ProfessionalSecurity Screen',
    ProfessionalPrivacyPolicyScreen:'ProfessionalPrivacyPolicy Screen',
    ProfessionalViewServicesScreen:'ProfessionalViewServicesScreen',
    ProfessionalViewInnerServicesScreen:'ProfessionalViewInnerServicesScreen',
    ProfessionalBookingScreen:'ProfessionalBookingScreen',
    ProfessionalInboxScreen:'ProfessionalInboxScreen',
    ProfessionalChatScreen:'ProfessionalChatScreen',
    ProfessionalCancelbookingScreen:'ProfessionalCancelbookingScreen',
    ProfessionalCancelledScreen:'ProfessionalCancelledScreen',
    ProfessionalCompletedScreen:'ProfessionalCompletedScreen',
    ProfessionalUpcomingScreen:'ProfessionalUpcomingScreen',
    ProfessionalScheduleScreen:'ProfessionalScheduleScreen',
    ProfessionalPrivacyAndPolicyScreen:'ProfessionalPrivacyAndPolicyScreen',
    ProfessionalSettingScreen:'ProfessionalSettingScreen',
    ProfessionalInnerServicesScreen:'ProfessionalInnerServicesScreen',
    ProfessionalConnectStripeScreen:'ProfessionalConnectStripeScreen',
    ProfessionalProfile2Screen:'ProfessionalProfile2Screen',
    LiveTrackingProfSideScreen:'LiveTrackingProfSideScreen',
    OrderProcessingScreenProfSideScreen:'OrderProcessingScreenProfSideScreen',
    profselectserviceScreen:'profselectserviceScreen',
    profselectedDetailserviceScreen:'profselectedDetailserviceScreen',
    professionalEditServiceScreen:'ProfessionalEditServiceScreen',

    FacilityBottomTab:'FacilityBottomTab',
    FacilityPrivacyAndPolicyScreen:'FacilityPrivacyAndPolicyScreen',
    FacilityOnBoardingScreen:'FacilityOnBoardingScreen',
    ConfirmationForCreateFacilitieScreen:'ConfirmationForCreateFacilitieScreen',
    FacilityConnectStripeScreen:'FacilityConnectStripe',
    FacilityHomeScreen:'FacilityHomeScreen',
    FacilityFacilitiesScreen:'FacilityFacilitiesScreen',
    FacilityHistoryScreen:'FacilityHistoryScreen',
    FacilityDetalisScreen:'FacilityDetalisScreen',
    FacilitySettingScreen:'FacilitySettingScreen',
    FacilityManageSeatScreen:'FacilityManageSeatScreen',
    FacilityViewMoreScreen:'FacilityViewMoreScreen',
    FacilityLeaderboardScreen:'FacilityLeaderboardScreen',
    FacilityGrossSalesScreen:'FacilityGrossSalesScreen',
    FacilityProsaledetailsScreen:'FacilityProsaledetailsScreen',
    FacilityCommissionsplitsScreen:'FacilityCommissionsplitsScreen',
    FacilityNextpayoutScreen:'FacilityNextpayoutScreen',
    FacilityProfile2Screen:"FacilityProfile2Screen",
    
}

export const label = {
    Exclusive: "Exclusive",
    HeaderDesc: "E-Pharmacy MrMed Secures $500,000 Funding from Tamil Nadu Emerging Sector Seed Fund",
    DHNUpdate: "DHN Updates That Matters",
    DigitalHealth: "DIGITAL\nHEALTH TECHNOLOGY",
    ReasonForAccountDelete: "Reason For Account Delete",
};

export const MenuItems = [
    "TODAY'S\nNEWS",
    "DIGITAL HEALTH\nTECHNOLOGY",
    "HOSPITALS AND\nGOVT. HEALTH IT",
    "MEDICAL DEVICES &\nDIAGNOSTIC",
    "DIGITAL HEALTH\nSTART-UP",
    "PHARMACEUTICALS AND\nBIOTECH",
    "GLOBAL DIGITAL\nHEALTH NEWS",
];

export const TopPopular = [
    "Today's Top Stories",
    "Popular Stories",
];

export const MenuDetails = [
    "DIGITAL HEALTH\nTECHNOLOGY",
    'HOSPITALS AND\nGOVT HEALTH IT',
    'MEDICAL DEVICES &\nDIAGNOSTICS',
    'DIGITAL HEALTH\nSTART-UP',
    'PHARMACEUTICALS\nAND BIOTECH',
    'GLOBAL DIGITAL\nHEALTH NEWS',
]

export const Details = {
    text: 'Zimmer Biomet India has unveiled the ‘Zimmer Biomet on Wheels’ campaign, aimed at bringing healthcare products and solutions to healthcare professionals across India.',
    desc: "\tThe 'Zimmer Biomet on Wheels' campaign is set to traverse 23,480 kilometres, covering key regions such as Delhi, Rajasthan, Punjab, Maharashtra, Gujarat, Tamil Nadu, Kerala, Telangana, Andhra Pradesh, and Uttar Pradesh over the next six months.\n\n\n\tKaustav Banerjee, vice president of South Asia at Zimmer Biomet, said, “With Zimmer Biomet on Wheels, we demonstrate our commitment to advancing innovation by bringing Zimmer Biomet's cutting-edge technologies to healthcare practitioners.” \n\n\n\tHe further emphasized the company's anticipation of the outcomes and insights gained from this initiative. \n\n\n\tZimmer Biomet seeks to establish fruitful partnerships with healthcare professionals across India as part of its ongoing mission to alleviate pain and enhance the quality of life for individuals worldwide. Zimmer Biomet is a global leader in medical technology, offering a comprehensive portfolio designed to enhance mobility and improve health. \n\n\n\tTheir range of innovative products and integrated digital and robotic technologies aim to enhance the patient experience while harnessing the power of data analytics and artificial intelligence. \n\n\n\tThe 'Zimmer Biomet on Wheels' campaign represents a bold step towards increasing access to innovative healthcare solutions for medical professionals across India through the adoption of cutting-edge technologies and solutions in the field of orthopaedics and sports medicine. In another development, in May this year, the Swedish multinational manufacturing corporation Volvo Group joined forces with Narayana Health to create an innovative mobile community clinic known as 'Wellness on Wheels.' \n\n\n\tThis mobile clinic was designed to offer free community screenings and medical services in rural areas of Karnataka and several other states in India. The “Wellness on Wheels” clinic has been customised and equipped with state-of-the-art medical equipment. \n\n\n\tThis advanced setup enables the screening and early detection of conditions such as cancer and heart disorders.",
    highlight: '“This journey will facilitate technology demonstrations, reaching over 1800 healthcare professionals from 200 hospitals and showcasing the transformative solutions offered by Zimmer Biomet.”',
}

export const EliteText = {
    text: 'Unlock Your Access to',
    text2: 'Dive deeper into the world of health and wellness with "DHN PLUS," your exclusive gateway to in-depth articles, expert opinions, and special features.',
    text3: 'Join "DHN PLUS" now to unlock a universe of premium health stories. Upgrade your health literacy today!'
}

export const SignUpText = {
    text: 'Sign In / Sign Up',
    text2: 'Sign In & Stay Updated With The Latest News And Analysis',
    text3: 'CONTINUE',
    text4: 'SIGN IN WITH',
    text5: 'SIGN IN WITH GOOGLE',
    text6: 'SIGN IN WITH FACEBOOK',
    text7: 'SIGN IN WITH APPLE',
}

export const ForumHeaderSliderData = [
    'about event',
    'register',
    'become a sponsor',
    'agenda',
    'speakers',
]
